l1 = list(map(int, input().split()))
l2 = list(map(int, input().split()))
print(l1)
print(l2)
print(set(l1).difference(set(l2)))
print(set(l1).intersection(set(l2)))
print(list(set(l1).union(set(l2))))
